/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as HabitsIndexRouteImport } from './routes/habits/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as NotesNewRouteImport } from './routes/notes/new'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as HabitsNewRouteImport } from './routes/habits/new'
import { Route as HabitsHabitIdRouteImport } from './routes/habits/$habitId'
import { Route as ContactsNewRouteImport } from './routes/contacts/new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsNewRoute = HabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/habits/$habitId',
  path: '/habits/$habitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/new': typeof HabitsNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/contacts': typeof ContactsIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/new': typeof HabitsNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/contacts': typeof ContactsIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/new': typeof HabitsNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/new': typeof NotesNewRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/contacts/': typeof ContactsIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/habits/$habitId'
    | '/habits/new'
    | '/notes/$noteId'
    | '/notes/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/contacts'
    | '/habits'
    | '/notes'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/habits/$habitId'
    | '/habits/new'
    | '/notes/$noteId'
    | '/notes/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/contacts'
    | '/habits'
    | '/notes'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/habits/$habitId'
    | '/habits/new'
    | '/notes/$noteId'
    | '/notes/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/contacts/'
    | '/habits/'
    | '/notes/'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsNewRoute: typeof ContactsNewRoute
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsNewRoute: typeof HabitsNewRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesNewRoute: typeof NotesNewRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/new': {
      id: '/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof HabitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsNewRoute: ContactsNewRoute,
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsNewRoute: HabitsNewRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesNewRoute: NotesNewRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
