export { authRoutes } from "./auth";
export { tasksRoutes } from "./tasks";
export { contactsRoutes } from "./contacts";
export { notesRoutes } from "./notes";
export { habitsRoutes } from "./habits";
export { categoriesRoutes } from "./categories";
export { oauthRoutes } from "./oauth";
export { carddavRoutes } from "./carddav";
export { mcpRoutes } from "./mcp";
